// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkx7uONXLG8HJpZ9iRJjaYqWXbZnix4n4',
    appId: '1:864215622075:web:208487b0af0049da41249e',
    messagingSenderId: '864215622075',
    projectId: 'sports-analyzer-sta',
    authDomain: 'sports-analyzer-sta.firebaseapp.com',
    storageBucket: 'sports-analyzer-sta.appspot.com',
    measurementId: 'G-39860XG4VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnAEC21G8PQym53u-UGR_Ng4qZPmCiyTI',
    appId: '1:864215622075:android:e3330e9c3d733aae41249e',
    messagingSenderId: '864215622075',
    projectId: 'sports-analyzer-sta',
    storageBucket: 'sports-analyzer-sta.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj-kJAmuEwZOu4KI2um8UcAoP_Co1A7r0',
    appId: '1:864215622075:ios:b8fe2cae428ce2ac41249e',
    messagingSenderId: '864215622075',
    projectId: 'sports-analyzer-sta',
    storageBucket: 'sports-analyzer-sta.appspot.com',
    iosClientId:
        '864215622075-h73bvhcadvvevnesuorpn7vl8ru2jj6q.apps.googleusercontent.com',
    iosBundleId: 'greene.chloe.STAAnalyzerSports',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj-kJAmuEwZOu4KI2um8UcAoP_Co1A7r0',
    appId: '1:864215622075:ios:7dc2f5c2dc5b095641249e',
    messagingSenderId: '864215622075',
    projectId: 'sports-analyzer-sta',
    storageBucket: 'sports-analyzer-sta.appspot.com',
    iosClientId:
        '864215622075-6p8flpdo1snescvjkeid5t7d9alagndj.apps.googleusercontent.com',
    iosBundleId: 'greene.chloe.STAAnalyzerSports.RunnerTests',
  );
}
